services:
  - type: web
    name: tellabook-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "flask run --host=0.0.0.0 --port=10000"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: FLASK_APP
        value: run:app
      - key: FLASK_RUN_PORT
        value: 10000
      - key: FLASK_ENV
        value: development
